# Generated by Django 4.2.28 on 2026-03-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.TextField(max_length=10000),
        ),
    ]
