# Generated by Django 4.2.28 on 2026-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_systemprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='prompts',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
