# Generated by Django 4.2.28 on 2026-03-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_systemprompt_prompts_alter_systemprompt_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompts',
            new_name='prompt',
        ),
    ]
