# Generated by Django 4.2.28 on 2026-03-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_prompts_systemprompt_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompt',
            new_name='prompts',
        ),
    ]
