# Generated by Django 4.2.28 on 2026-03-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_prompt_systemprompt_prompts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompts',
            new_name='prompt',
        ),
    ]
